[book]
authors = ["donghee"]
language = "ko"
multilingual = false
src = "chapters"
title = "비거니즘 전시 매뉴얼 ver.1"

[output.html]
default-theme = "vegan"
#git-repository-url = "https://github.com/donghee/zeromakeszero/tree/master/wiki"
#edit-url-template = "https://github.com/donghee/zeromakeszero/edit/master/wiki/{path}"
additional-js = ["chapters/assets/fzf.umd.js", "chapters/assets/elasticlunr.js"]

[output.html.playground]
editable = true
line-numbers = true

[output.html.search]
enable = true
#limit-results = 20
#use-boolean-and = true
#boost-title = 2
#boost-hierarchy = 2
#boost-paragraph = 1
#expand = true
#heading-split-level = 2

# https://github.com/badboy/mdbook-toc
[preprocessor.toc]
marker = "[[_TOC_]]"
max-level = 3
